# nixpacks.toml - CORRECTED for Railway
[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ttf_bitstream_vera",
  "fontconfig",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "gtk3",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libxcb",
  "libxkbcommon",
  "mesa",
  "expat",
  "alsaLib",
  "at-spi2-atk",
  "at-spi2-core",
  "cups",
  "dbus",
  "nspr",
  "glib"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node pointsbot.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"